return {
  'J3S5E/breadcrumb.nvim',
  dependencies = {
    'nvim-tree/nvim-web-devicons',
  },
  event = { 'BufReadPre', 'BufNewFile' },
  opts = {
    icons = {
      File = ' ',
      Module = '󰕳 ',
      Namespace = ' ',
      Package = ' ',
      Class = ' ',
      Method = ' ',
      Property = ' ',
      Field = ' ',
      Constructor = ' ',
      Enum = ' ',
      Interface = ' ',
      Function = '󰊕 ',
      Variable = '󰫧 ',
      Constant = ' ',
      String = ' ',
      Number = ' ',
      Boolean = ' ',
      Array = '󰅪 ',
      Object = '󰅩 ',
      Key = '󰌆 ',
      Null = '󰟢 ',
      EnumMember = ' ',
      Struct = ' ',
      Event = ' ',
      Operator = ' ',
      TypeParameter = ' ',
    },
    separator = '',
    highlight_group = {
      component = 'lualine_c_normal',
      separator = 'lualine_c_normal',
    },
  },
}
